---
title: "Overview"
---

This page contains general instructions for assignments/peer reviews. For homework-specific instructions, deadlines, and templates, go to the specific assignment listed on the left. 

---

All assignments should be created using Quarto and uploaded to Canvas as both html and qmd files. Your document should be pleasant for a peer to look at and follow all instructions. Use sections for organization, label figures/tables, and use code chunks (e.g., `echo`, `results`).

### **Peer Review:**

You are required to **both grade and provide feedback** on a peer's homework each week. Reading/evaluating the work of others is useful and important! Good programmers realize that most problems have been solved by others; the trick is figuring out how to apply existing code to new problems. You will develop this skill by reading others\' code, evaluating their approach to problems, providing suggestions, and pointing out when you learned something new. **Good peer reviews** give constructive, polite, and insightful comments, are specific and concise, use the grading rubric below, and point out what you learned from their code. **Poor peer reviews** are impolite or unprofessional, are generic (i.e., could be applied to anyone\'s homework), or fail to provide useful suggestions.

### **Rubric Students Use to Grade Assignments:**

\
**0:** Didn\'t turn anything in\
**1:** Turned in but low effort, ignoring many directions (less than 50% of assignment completed correctly)\
**2:** Decent effort, followed directions with some minor issues (50-80% of assignment completed correctly)\
**3:** Nailed it (\>80% of assignment completed correctly)

### **Rubric Instructor Uses to Grade Peer Review:**

\
**0:** Didn't follow all of the instructions below.\
**1:** Peer review was at least one paragraph long, mentions any and all key issues from the assignment, and points out at least one thing positive in your peer's work (and hopefully more!).

### **When to Contact the Instructor:**

A number of situations may warrant contacting the instructor:

1.  If you believe you have received an unfair peer review, you can **resubmit** your homework for evaluation by the instructor. The assignment will be regraded, which may result in a higher, same, or lower grade.

2.  If you wish for more feedback on a particular part of the homework, you can ask the instructor for additional explanation **without resubmitting** during lab or over email.

3.  If you receive no feedback, the instructor will provide gentle peer review **on request**.
