---
title: "Tips & Tricks"
format: 
  html:
    code-annotations: hover
    highlight-style: a11y-dark
---

Here're all the shortcuts/tips & tricks you gathered from the [RStudio Tips Twitter account](https://twitter.com/rstudiotips). 

:::: {.columns}

::: {.column width="49%"}
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you click on the R hex icon in <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a>&#39;s Files pane, it brings you back to the top-level folder of your Project, if you&#39;ve navigated away. I use this all the time and I want to make sure you know about it. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/7NcbXyMZzs">pic.twitter.com/7NcbXyMZzs</a></p>&mdash; Jenny Bryan (@JennyBryan) <a href="https://twitter.com/JennyBryan/status/1460296605186228224?ref_src=twsrc%5Etfw">November 15, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Do you use <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> on a laptop? You can use Shift + Ctrl + 2 to work in just the console for a while. Try Shift + Ctrl + 1 for a distraction-free editing experience, too! <a href="https://t.co/jYtzrojaFl">https://t.co/jYtzrojaFl</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/958412524877004800?ref_src=twsrc%5Etfw">January 30, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Coming in <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> 1.3: real time spellchecking! <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/wPuX9Ku8az">https://t.co/wPuX9Ku8az</a> <a href="https://t.co/sBQ3gfb6vU">pic.twitter.com/sBQ3gfb6vU</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1227320322258501642?ref_src=twsrc%5Etfw">February 11, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">command + option + i for new set of code<br>command + shift + m for piping</p>&mdash; Dr. Benjamin W. Nelson (@benjaminwnelson) <a href="https://twitter.com/benjaminwnelson/status/1333905138386350086?ref_src=twsrc%5Etfw">December 1, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">TIL: You can run function examples from the Viewer Pane in RStudio by just selecting text and hitting Ctrl+Enter, like you can with code in the Source panel. How great is that?! (This is not new, it&#39;s been around since 2017, but I wasn&#39;t aware of it) <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/9edFPhG73P">pic.twitter.com/9edFPhG73P</a></p>&mdash; Nic Crane (@nic_crane) <a href="https://twitter.com/nic_crane/status/1394223496029511682?ref_src=twsrc%5Etfw">May 17, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The true purpose of my existence is to teach students to use the appropriate shortcut to execute <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> commands in <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@RStudio</a> <a href="https://t.co/1rTAIASURj">pic.twitter.com/1rTAIASURj</a></p>&mdash; Francois Keck (@FrancoisKeck) <a href="https://twitter.com/FrancoisKeck/status/1560675721420632064?ref_src=twsrc%5Etfw">August 19, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Don&#39;t touch that mouse! Jump quickly between the source and console via keyboard: Ctrl+1 to focus source, Ctrl+2 to focus console. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/lHOpd9TNnr">pic.twitter.com/lHOpd9TNnr</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/817440693266194432?ref_src=twsrc%5Etfw">January 6, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Our <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> add-in of the day is Esquisse: <a href="https://t.co/PrZX1z6vbP">https://t.co/PrZX1z6vbP</a>. It&#39;s kind of a mash-up of an interactive data explorer and ggplot2 builder: quickly slice your data into beautiful plots *and* create reproducible code for them at the same time. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/4j8KbZD7LA">pic.twitter.com/4j8KbZD7LA</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1451591686270767105?ref_src=twsrc%5Etfw">October 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">New to me: <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> users in <a href="https://twitter.com/hashtag/RStudio?src=hash&amp;ref_src=twsrc%5Etfw">#RStudio</a> can use Control + P to jump between matching parentheses. Handy especially for nesting in <a href="https://twitter.com/hashtag/RShiny?src=hash&amp;ref_src=twsrc%5Etfw">#RShiny</a> apps, perhaps. <a href="https://t.co/nfSROX5b37">https://t.co/nfSROX5b37</a></p>&mdash; Matt Dray (@mattdray) <a href="https://twitter.com/mattdray/status/1432292336969699334?ref_src=twsrc%5Etfw">August 30, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Missed your chance to pick up an <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> cheat sheet at <a href="https://twitter.com/hashtag/useR2016?src=hash&amp;ref_src=twsrc%5Etfw">#useR2016</a>? We&#39;ve put them in the Help menu too. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/QbHKWqvUdu">pic.twitter.com/QbHKWqvUdu</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/750729452150071296?ref_src=twsrc%5Etfw">July 6, 2016</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Want to remember when you wrote a section of R script? Type &quot;ts&quot; and press Shift+Tab to insert a section header w/ timestamp. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/RLTfzlJzDh">pic.twitter.com/RLTfzlJzDh</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/807278080750284800?ref_src=twsrc%5Etfw">December 9, 2016</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Our <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> add-in of the day is todor by <a href="https://twitter.com/dokatox?ref_src=twsrc%5Etfw">@dokatox</a>. Never miss a TODO in your R project again! <a href="https://t.co/xWUnvaHgZE">https://t.co/xWUnvaHgZE</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/LR00tRhNLA">pic.twitter.com/LR00tRhNLA</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1128700643579842560?ref_src=twsrc%5Etfw">May 15, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Organize and navigate your R scripts with sections: press Ctrl+Shift+R (OS X: Cmd+Shift+R) to insert one. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="http://t.co/beVnsmTUVV">pic.twitter.com/beVnsmTUVV</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/653978432095649792?ref_src=twsrc%5Etfw">October 13, 2015</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">New <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> 1.4 Preview has a command palette: run any command or addin and change settings with just a few keystrokes. No mouse required! <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/yIhQklEzi5">https://t.co/yIhQklEzi5</a> <a href="https://t.co/ndFwE3kU82">pic.twitter.com/ndFwE3kU82</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1316407947082125312?ref_src=twsrc%5Etfw">October 14, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">My absolute favorite RStudio add-in: imageclipr. Seamlessly paste images from the clipboard into R Markdown files. What is this voodoo? <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/rstudiotips?ref_src=twsrc%5Etfw">@rstudiotips</a> <a href="https://t.co/DMdmbsQVwn">https://t.co/DMdmbsQVwn</a> <a href="https://t.co/ZM9cG3eSGt">pic.twitter.com/ZM9cG3eSGt</a></p>&mdash; Zachary Fisher (@fishingwithzack) <a href="https://twitter.com/fishingwithzack/status/1297231478657626112?ref_src=twsrc%5Etfw">August 22, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
:::

::: {.column width="2%"}
:::

::: {.column width="49%"}
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Quick, what&#39;s inside that data frame? Hold down Ctrl (Cmd on macOS) and click on the name of an object in the editor to view its contents. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/6E86M55jLH">pic.twitter.com/6E86M55jLH</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1422247399217504283?ref_src=twsrc%5Etfw">August 2, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Did you know that <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> has a real-time LaTeX equation previewer? Create a math block with \$$ in your R Markdown document to try it out. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/TneXdaOVJW">pic.twitter.com/TneXdaOVJW</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/964562660351033344?ref_src=twsrc%5Etfw">February 16, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<p align="center"> <span style="color:red">{{< fa down-long >}}</span><span style="color:red">{{< fa down-long >}}</span><span style="color:red">{{< fa down-long >}}</span> **BE CAREFUL WITH THIS ONE!**^[Editing datasets in this way is not reproducible unless this also generates the code required to make those changes and you save that code in your source document. **Proceed with caution.**] <span style="color:red">{{< fa down-long >}}</span><span style="color:red">{{< fa down-long >}}</span><span style="color:red">{{< fa down-long >}}</span> </p>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr"> Ever wanted an *editable* data view in <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a>? We didn&#39;t make one, but <a href="https://twitter.com/DillonHammill?ref_src=twsrc%5Etfw">@dillonhammill</a> did. Add-in here: <a href="https://t.co/YJFrsxCzkZ">https://t.co/YJFrsxCzkZ</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/iyqClHK9hj">pic.twitter.com/iyqClHK9hj</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1500888862318469120?ref_src=twsrc%5Etfw">March 7, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Our <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> add-in of the day is ViewPipeSteps by <a href="https://twitter.com/daranzolin?ref_src=twsrc%5Etfw">@daranzolin</a>: make it easier to see what every step in a pipeline does by examining the data at each point in the transformation! <a href="https://t.co/XbKoXy3mml">https://t.co/XbKoXy3mml</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/w4st4WgQU5">pic.twitter.com/w4st4WgQU5</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1178758711575105536?ref_src=twsrc%5Etfw">September 30, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Wrapping library calls with curly brackets, benefits: collapsible within RStudio and can be run interactively as one line using Ctrl+Enter <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/TIL?src=hash&amp;ref_src=twsrc%5Etfw">#TIL</a> <a href="https://t.co/nfuggOdZnw">https://t.co/nfuggOdZnw</a> <a href="https://t.co/k3YpZvWBfz">pic.twitter.com/k3YpZvWBfz</a></p>&mdash; Tokhir Dadaev (@zx8754) <a href="https://twitter.com/zx8754/status/1610281796834365440?ref_src=twsrc%5Etfw">January 3, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Did you know that <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> makes a great <a href="https://twitter.com/hashtag/markdown?src=hash&amp;ref_src=twsrc%5Etfw">#markdown</a> editor? Save file as .md and press Ctrl+Shift+K to view. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/tnZ5H5rBu4">pic.twitter.com/tnZ5H5rBu4</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/766684921041608705?ref_src=twsrc%5Etfw">August 19, 2016</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you want to get the full path to a file you have open in <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a>, hold the mouse over the tab for a second or two. <br><br>(Also useful: Session &gt; Set Working Directory &gt; To Source File Location, which can be bound to a keyboard shortcut!) <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/NShZ7JJ9Wj">https://t.co/NShZ7JJ9Wj</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/977218566243082240?ref_src=twsrc%5Etfw">March 23, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Our <a href="https://twitter.com/hashtag/rstudio?src=hash&amp;ref_src=twsrc%5Etfw">#rstudio</a> add-in of the day is Codegrip, which makes it easy to beautifully format R function calls (especially long ones) and navigate inside them. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a><a href="https://t.co/8wHlWZH0mo">https://t.co/8wHlWZH0mo</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1632818003321683968?ref_src=twsrc%5Etfw">March 6, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Ctrl+Shift+A reformats your selection in <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> -- unless, of course, it is already perfect. <a href="https://t.co/GtwzW3ekkG">https://t.co/GtwzW3ekkG</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/946793718874542080?ref_src=twsrc%5Etfw">December 29, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I just discovered that scripts in multiple panels was a layout option in <a href="https://twitter.com/hashtag/rstudio?src=hash&amp;ref_src=twsrc%5Etfw">#rstudio</a>. This is so handy! <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/rtips?src=hash&amp;ref_src=twsrc%5Etfw">#rtips</a> <br><br>Tools &gt; Global Options &gt; Pane Layout <a href="https://t.co/UKywpb3p9t">pic.twitter.com/UKywpb3p9t</a></p>&mdash; Karissa Whiting (@karissawhiting) <a href="https://twitter.com/karissawhiting/status/1588568354696343552?ref_src=twsrc%5Etfw">November 4, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Ctrl+r for searching previous commands</p>&mdash; Erika Salomon (@ecsalomon) <a href="https://twitter.com/ecsalomon/status/1431232111181172740?ref_src=twsrc%5Etfw">August 27, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Do you use SQL with R? With R Markdown and R Notebooks, you can run SQL statements right inside the editor. <a href="https://t.co/4IG1QWIkz6">https://t.co/4IG1QWIkz6</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/3dyKBUwBOq">pic.twitter.com/3dyKBUwBOq</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/800761452361486336?ref_src=twsrc%5Etfw">November 21, 2016</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The new Jobs pane in the <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a> 1.2 Preview lets you run your R scripts in the background. Learn how to use it: <a href="https://t.co/x8JZ6kSjQm">https://t.co/x8JZ6kSjQm</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/omEgjpCkis">pic.twitter.com/omEgjpCkis</a></p>&mdash; RStudio Tips (@rstudiotips) <a href="https://twitter.com/rstudiotips/status/1106239069644677120?ref_src=twsrc%5Etfw">March 14, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Did you know you can knit an R script? <br><br>In <a href="https://twitter.com/rstudio?ref_src=twsrc%5Etfw">@rstudio</a>, add 6 lines to the start of your script, write text using #&#39;, and File -&gt; Knit. Github friendly way of sharing a mostly-code report with collaborators <a href="https://t.co/UV7rX0eDe3">https://t.co/UV7rX0eDe3</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/8upPX9mf4Z">pic.twitter.com/8upPX9mf4Z</a></p>&mdash; James Robinson (@jamespwr) <a href="https://twitter.com/jamespwr/status/1389916296171724803?ref_src=twsrc%5Etfw">May 5, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
:::

::::










