---
title: "Homework 8"
highlight-style: a11y-dark
---

### [Key](homework8_key.qmd)

Click link above for answers to homework 8.

### Instructions
Answer each of the following questions. Be sure to display **all your code in the rendered** version (use `echo: true` throughout[^longnote]). 

[^longnote]: You can make this a global option for your whole document by putting it directly in the YAML of your qmd:

    ```{YAML}
    ---
    title: "My Document"
    execute:
      echo: true
    ---
    ```

### Exercises

#### Question 1: 

Given a vector of birthdates^[Assume `mdy` format for this vector.], write a function to compute the age in years^[Depending upon how you want to solve this problem, the lubridate functions `today()` and `time_length()` could be useful here :)].

#### Question 2: 

For each of the following functions list all arguments that use tidy evaluation and describe whether they use data-masking or tidy-selection: `distinct()`, `count()`, `group_by()`^[Note: `group_by()` doesn't list what type of tidy evaluation it uses for its `...` argument but you can find the answer in the introduction to [this](https://dplyr.tidyverse.org/articles/programming.html) article.], `rename_with()`, `slice_min()`, `slice_sample()`.

#### Question 3:

Build up a rich plotting function by incrementally implementing each of the steps below:

* Draw a scatterplot given `dataset` and `x` and `y` variables.
* Add a line of best fit (i.e. a linear model with no standard errors)^[`geom_smooth()` has a `method` and `se` argument that will be necessary to specify here.].  
* Add a title that includes the names of the variables used.

Test your function with the built-in `cars`, `swiss`, and `iris` datasets.

### Due Dates

```{r}
#| echo: false
#| message: false
#| warning: false

# reading in base due date schedule
source("../due_dates_schedule.R")

make_due_date_table_spring(8) |> 
  tab_options(table.background.color = "#f6f7f9")
```