---
title: "Homework 6"
highlight-style: a11y-dark
---

### Instructions
Answer each of the following questions. Be sure to display **all your code in the rendered** version (use `echo: true` throughout[^longnote]). 

[^longnote]: You can make this a global option for your whole document by putting it directly in the YAML of your qmd:

    ```{YAML}
    ---
    title: "My Document"
    execute:
      echo: true
    ---
    ```

### Exercises
1. Vectors
  i. `LETTERS` contains the 26 capital letters in order. Use `LETTERS` and `[ ]` to create a vector of the first 13 capital letters.
  ii. `letters` contains the 26 lowercase letters in order. Use `fct`, `letters`, and `[ ]` to create a factor variable using the last 13 lower case letters.
  iii. Use `rev()` to reverse the order of `vec_fac`.
  iv. Use `:` to create an integer vector of the numbers 11 through 20.
  v. If you used `c()` to combine `vec_int` with `vec_fac`, what class of vector would you get? Why?
  vi. Consider the vector `c(TRUE, FALSE, TRUE, TRUE)`. What happens to its values when you try to convert it to numeric? To character? To numeric and then character?
  
2. Matrices
  i. 



### Due Dates

```{r}
#| echo: false
#| message: false
#| warning: false

# reading in base due date schedule
source("../../Lectures/due_dates_schedule.R")

make_due_date_table(6) |> 
  tab_options(table.background.color = "#f6f7f9")
```